### ISSUE TITLE
How to view the function's man page in RDocumentation panel with `?`

### ISSUE THREAD

**Issue by MarcinKosinski** [datacamp/RDocumentation#61] opened 2016-11-17 15:02 UTC
I get the empty panel for `?` calls to the documentation of any function like below

![t_test](https://cloud.githubusercontent.com/assets/6773454/20394282/45749ab4-acdf-11e6-8e92-7c6e0de8e013.png)

**Comment by filipsch** [comment] 2016-11-30 17:12
This should be fixed now.

**Closed by filipsch** 2016-11-30 17:12 UTC
Labels: bug

**Comment by MarcinKosinski** [comment] 2016-11-30 17:53
Can you provide a commit to this issue? Or extend commit messegaes with `#issues_number` so that they appear automatically in the issue's conversation tree

**Comment by filipsch** [comment] 2016-12-01 08:52
@MarcinKosinski this fix is the result of a more bigger rewrite in general:
- https://github.com/datacamp/RDocumentation/commit/8b2f14b023fcfbbd72a5be72de6b2f818090f2de
- https://github.com/datacamp/RDocumentation/commit/bed38a239670ea6ce198d72529772e375920b270

When the issue is fixed by a very specific commit, we should indeed reference the issue specifically in our message.
